baseURL = "https://lanazwart.github.io/lzseevee/"
languageCode = "en-us"
title = "My New Online CV"
theme = "ananke"
publishDir = "docs"

# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lana Zwart Online CV"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/budparr/gohugo-theme-ananke"
tags = ["website", "starter", "responsive"]
features = ["posts", "shortcodes"]
min_version = 0.25

[author]
  name = "Bud Parr"
  homepage = "https://github.com/budparr"
